server:
  port: 80

ribbon:
  # Needed for connection to product-service, because of long(er) response time from Spotify & Discogs
  ReadTimeout:    10000

zuul:
  ignored-services: "*"
  ignoredPatterns:
    - "/actuator/**"
    - "/authenticated"
  routes:
    spotify-service:
      path:             "/spotify/**"
      service-id:       spotify-service
      strip-prefix:     true
      sensitiveHeaders: Cookie,Set-Cookie
    discogs-service:
      path:             "/discogs/**"
      service-id:       discogs-service
      strip-prefix:     false
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
    product-service:
      path:             "/product/**"
      service-id:       product-service
      strip-prefix:     true
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
    frontend:
      path:             "/**"
      service-id:       frontend
      stripPrefix:      false
      sensitiveHeaders: Cookie,Set-Cookie,Authorization

eureka:
  instance:
    prefer-ip-address: true